# Generated by Django 2.2.17 on 2020-11-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201110_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('create_date',)},
        ),
    ]
