# Generated by Django 2.2.17 on 2020-11-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201111_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-create_date',)},
        ),
    ]
